name: Test and lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main, ian/ai-v5]
  pull_request:
    branches: ["**"]

jobs:
  check:
    name: Test and lint
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Node setup
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18.20.8"

      - name: Install dependencies
        run: |
          npm i
          npm run build
          cd example && npm i
      - name: pkg-pr-new
        run: npx pkg-pr-new publish .
      - name: Test
        run: |
          npm run test
          npm run typecheck
          npm run lint
          cd example
          npm run lint
